# 0.2232 This is a basic workflow to help you get started with Actions

name: auto-merge 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the branch-0.2 branch
on:
  schedule:
  - cron: '*/10 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  automerge:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: auto-merge job
      uses: docker://pxli/automerge:latest
      env:
        OWNER: pxLi
        REPO_NAME: spark-rapids
        HEAD: branch-0.2
        BASE: branch-0.3
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
