name: caller

on:
  pull_request:
    types: [edited]
  pull_request_target:
    types: [edited]

jobs:
  signoff-check:
    if: ${{ github.event.changes.base.ref.from != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: call_signoff-check
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: ./.github/workflows/signoff-check
        
      - name: call_mvn-verify-check
        if: ${{ github.event_name == 'pull_request' }}
        uses: ./.github/workflows/mvn-verify-check
