name: caller

on:
  pull_request:
    types: [edited]
  pull_request_target:
    types: [edited]

jobs:


  signoff-check:
    if: ${{ github.event.changes.base.ref.from != '' }}
    runs-on: ubuntu-latest
    steps:
      call_signoff-check:
        runs-on: ubuntu-latest
        steps:
          - uses: ./.github/workflows/signoff-check
